### PR TITLE
Private-events with Ruby on Rails / ActiveRecord

### PR DESCRIPTION
**Pull request by Milypm**
*Note: I worked alone/solo on this project.

This project consists of a Ruby on Rails application, where users can create accounts (just with a username) and events through ActiveRecord associations, having many to many relationships between the models.

- A user must be registered and logged in to be able to see, create and attend events.
- A user can edit or delete her/his own account, and her/his own events.
- A user can attend multiple events, and unattend them.

Built With
- Ruby (v. 2.7.2 / 3.0.0)
- Ruby on Rails (v. 6.1.1)
- HTML / CSS (Bootstrap)
- Rubocop
- RSpec and Capybara for testing
- Git

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @Milypm, 👋🏽 
 **Thank you for the good job you got going on. The Private event app looks good and is more user-friendly. The readme file is also detailed. 👍🏽 The tests cover a wide scenario base 💃🏽**

## REQUIRED CHANGES 🔴 🟡 

- [x] Kindly add to the readme file the procedures to follow when testing your app.
- [x] The index action in the events controller should list both the [past](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) and [upcoming](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) events as required from [odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)).
```
@past_events = Event.previous_events
@upcoming_events = Event.upcoming_events
```

## The show action in Users controller
- [x]  should lists events created by user, i.e. `@created_events = current_user.events`. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [x] Also, lists events previoulsy attended by user using event model scope, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)).
- [x] Again, lists upcoming events previously attended by user using event model scope, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- [x] OPTIONAL A logged-in user should only delete an event they created.

**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding. 💻 

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required 🛑 

### Hello team 👋,

**Great job implementing the requested changes 👏.**

### Highlights

- **The application has a great design.**
- **The application follows all the project-specific requirements.**

### Mandatory Requirements.

1). **Please implement the changes requested by the previous TSE about the index action in the events controller and the show action in users controller.**

2). **Please remove the logic (if statements and each loop) in the following view files**

- `users/show.html.erb`
- `layouts/_header.html.erb`
- `events/index.html.erb`
- `events/show.html.erb`

**see a [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) of the above requirement in pathwright.**
**Hint: Check out this [article](https://dev.to/saintaze/rendering-list-items-in-ruby-on-rails-6-48ae) on how to render lists.**


### Happy coding 🥂.

**You can reach me on slack (Rose Wanjohi).**

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Mily Puente Morones** 
Good job with the improvements for this project :muscle:  :muscle:
It looks amazing :clap: :clap: :clap:  
Just a couple of details to improve before you can go ahead:

- [x] Fix rubocop offenses
- [x] Add integration tests
 
Please request another review once you are ready! :+1: 

Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by whiz25 — APPROVED** [review]
## Approved ✅ 
Amazing job @Milypm. You added integration tests as requested and rubocop doesn't shoe errors. Merge and proceed to the next project.



### Martin Afani

**Pull request merged**
